# Generated by Django 2.2.2 on 2019-06-25 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0004_transaction_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionableImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='auctionable_images/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bidding.Auctionable')),
            ],
        ),
    ]
